data:
  build: docker/data
  volumes:
   - .:/project
php:
  build: docker/php-fpm
  volumes_from:
   - data
composer:
  build: docker/composer
  volumes_from:
    - data
nginx:
  build: docker/nginx
  ports:
   - "80:80"
  links:
   - php
  volumes_from:
   - data
