data:
  build: docker-data
  volumes:
   - .:/project
   - docker-data/sites:/etc/nginx/sites-enabled
   - docker-data/redis:/data:rw
   - docker-data/postgres:/var/lib/postgresql/data
redis:
  image: redis:3.0
  expose: 
   - "6379"
  volumes_from:
   - data
  command: ["/usr/local/bin/redis-server", "--appendonly", "yes"]
postgres:
  image: postgres
  environment:
   - POSTGRES_PASSWORD=1111
   - POSTGRES_USER=root
   - LC_ALL=C.UTF-8
  volumes_from:
   - data
php:
  image: gidman/desk-docker-php7
  links:
   - redis
   - postgres
  volumes_from:
   - data
nginx:
  image: gidman/desk-docker-nginx
  ports:
   - "80:80"
  links:
   - php
  volumes_from:
   - data
