data:
  build: docker-data
  volumes:
   - .:/project
   - docker-data/sites:/etc/nginx/sites-enabled
php:
  image: gidman/desk-docker-php7
  volumes_from:
   - data
nginx:
  image: gidman/desk-docker-nginx
  ports:
   - "80:80"
  links:
   - php
  volumes_from:
   - data
